num1 = int(input ("ye adad benvis: "))
num2 = int(input ("ye adad dige: "))
sum = (num1 + num2)
tafrigh = (num1 - num2)
zarb = (num1 * num2)
taghsim = (num1 / num2)
print (sum)
print (tafrigh)
print (zarb)
print (taghsim)
